#services:
 # db:
  #  image: mcr.microsoft.com/mssql/server:2022-latest
  #  container_name: sqlserver-db
  #  ports:
  #    - "1433:1433"
  #  environment:
  #    ACCEPT_EULA: "Y"
  #    SA_PASSWORD: "AstrumDReamer73"
  #  volumes:
  #    - sql_data:/var/opt/mssql
   # restart: always

 # app:
  #  build: .
  #  container_name: spring-app
  #  ports:
   #   - "8080:8080"
   # depends_on:
   #   - db
   # environment:
   #   SPRING_DATASOURCE_URL: jdbc:sqlserver://db:1433;databaseName=ProyectoResidencias;encrypt=true;trustServerCertificate=true
   #   SPRING_DATASOURCE_USERNAME: sa
   #   SPRING_DATASOURCE_PASSWORD: AstrumDReamer73
   # restart: always

#volumes:
 # sql_data:

#version: '3.8'
#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#
#    volumes:
#      - uploads-data:/app/data
#
#    depends_on:
#      db:
#        condition: service_healthy
#
#    environment:
#      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
#      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
#      - MAIL_USERNAME=${MAIL_USERNAME}
#      - MAIL_PASSWORD=${MAIL_PASSWORD}
#
#  db:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    ports:
#      - "1433:1433"
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=${SA_PASSWORD}
#      - MSSQL_PID=Express
#    volumes:
#      - db-data:/var/opt/mssql
#
#volumes:
#  db-data:
#  uploads-data: